### ISSUE TITLE
A4.2.A As a group, create a new feature that provides a health check

### ISSUE THREAD

**Issue by manlopalm** [gii-is-psg2/PSG2-2021-G8-82#77]
This feature has to be implemented using the branching strategy defined in the Sprint S2. Regarding security, the health check endpoint should be accessible without authentication.

**Comment by carcabcol** [comment]
Follosing this tutorial: [https://spring.io/guides/gs/actuator-service/](https://spring.io/guides/gs/actuator-service/)
